version: '3.8'

services:
  backend:
    build: .
    container_name: atarax_backend
    ports:
      - "8008:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    restart: unless-stopped