# Generated by Django 6.0.5 on 2026-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
            ],
            options={
                'verbose_name': 'NPC postava',
                'verbose_name_plural': 'NPC postavy',
            },
        ),
    ]
