# Generated by Django 6.0.5 on 2026-09-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('type', models.CharField(choices=[('kontinent', 'Kontinent'), ('království', 'Království'), ('region', 'Region'), ('město', 'Město'), ('specifická lokace', 'Specifická lokace')], max_length=100, verbose_name='Typ')),
                ('specific_location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specifická lokace')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_locations', to='atarax_backend_app.location', verbose_name='Město')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continent_locations', to='atarax_backend_app.location', verbose_name='Kontinent')),
                ('kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kingdom_locations', to='atarax_backend_app.location', verbose_name='Království')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_locations', to='atarax_backend_app.location', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Lokace',
                'verbose_name_plural': 'Lokace',
            },
        ),
    ]
