# Generated by Django 6.0.5 on 2026-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('continent', models.CharField(choices=[('Erthiniel', 'Erthiniel')], max_length=100, verbose_name='Kontinent')),
                ('kingdom', models.CharField(choices=[('Test Kingdom', 'Test Kingdom')], max_length=100, verbose_name='Království')),
                ('region', models.CharField(choices=[('Test Region', 'Test Region')], max_length=100, verbose_name='Region')),
                ('city', models.CharField(choices=[('Test City', 'Test City')], max_length=100, verbose_name='Město')),
            ],
            options={
                'verbose_name': 'Lokace',
                'verbose_name_plural': 'Lokace',
            },
        ),
    ]
