# Generated by Django 6.0.5 on 2026-09-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('npc_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc_locations', to='atarax_backend_app.location', verbose_name='Lokace')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPC',
            },
        ),
    ]
