# Generated by Django 6.0.5 on 2026-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0002_npc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='npc_location',
            new_name='npc_location_id',
        ),
        migrations.AddField(
            model_name='npc',
            name='npc_location_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Jméno lokace'),
        ),
    ]
