# Generated by Django 6.0.5 on 2026-09-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0002_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Město',
                'verbose_name_plural': 'Města',
            },
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Kontinent',
                'verbose_name_plural': 'Kontinenty',
            },
        ),
        migrations.CreateModel(
            name='Dungeons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Dungeon',
                'verbose_name_plural': 'Dungeony',
            },
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.continents', verbose_name='Kontinent')),
            ],
            options={
                'verbose_name': 'Království',
                'verbose_name_plural': 'Království',
            },
        ),
        migrations.CreateModel(
            name='Mobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Mob',
                'verbose_name_plural': 'Moby',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.kingdom', verbose_name='Království')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiony',
            },
        ),
        migrations.CreateModel(
            name='unique_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Unikátní lokace',
                'verbose_name_plural': 'Unikátní lokace',
            },
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='dungeons',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region'),
        ),
    ]
