# Generated by Django 6.0.5 on 2026-09-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0003_city_continents_dungeons_kingdom_mobs_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='city_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.city', verbose_name='Město'),
        ),
        migrations.AddField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='npc',
            name='dungeon_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.dungeons', verbose_name='Dungeon'),
        ),
        migrations.AddField(
            model_name='npc',
            name='other_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.unique_location', verbose_name='Unikátní lokace'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='dungeons',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.continents', verbose_name='Kontinent'),
        ),
        migrations.AlterField(
            model_name='region',
            name='kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.kingdom', verbose_name='Království'),
        ),
        migrations.AlterField(
            model_name='unique_location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.region', verbose_name='Region'),
        ),
    ]
