# Generated by Django 6.0.5 on 2026-09-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0004_npc_city_location_npc_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '4 - Město', 'verbose_name_plural': 'Města'},
        ),
        migrations.AlterModelOptions(
            name='continents',
            options={'verbose_name': '1 - Kontinent', 'verbose_name_plural': 'Kontinenty'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'verbose_name': '2 - Království', 'verbose_name_plural': 'Království'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '3 - Region', 'verbose_name_plural': 'Regiony'},
        ),
        migrations.AlterField(
            model_name='npc',
            name='city_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.city', verbose_name='Město (pokud je)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='dungeon_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.dungeons', verbose_name='Dungeon (pokud je)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='other_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atarax_backend_app.unique_location', verbose_name='Unikátní lokace (pokud je)'),
        ),
    ]
