# Generated by Django 6.0.5 on 2026-09-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0005_alter_city_options_alter_continents_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('type', models.CharField(choices=[('kontinent', 'Kontinent'), ('království', 'Království'), ('region', 'Region'), ('město', 'Město'), ('specifická lokace', 'Specifická lokace')], max_length=100, verbose_name='Typ')),
                ('continent', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kontinent')),
                ('kingdom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Království')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Město')),
                ('specific_location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specifická lokace')),
            ],
            options={
                'verbose_name': 'Lokace',
                'verbose_name_plural': 'Lokace',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='city_location',
        ),
        migrations.RemoveField(
            model_name='kingdom',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='dungeons',
            name='region',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='dungeon_location',
        ),
        migrations.RemoveField(
            model_name='region',
            name='kingdom',
        ),
        migrations.DeleteModel(
            name='Mobs',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='other_location',
        ),
        migrations.RemoveField(
            model_name='unique_location',
            name='region',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Continents',
        ),
        migrations.DeleteModel(
            name='Dungeons',
        ),
        migrations.DeleteModel(
            name='Kingdom',
        ),
        migrations.DeleteModel(
            name='NPC',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='unique_location',
        ),
    ]
