# Generated by Django 6.0.5 on 2026-09-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atarax_backend_app', '0006_location_remove_city_region_remove_npc_city_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_locations', to='atarax_backend_app.location', verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continent_locations', to='atarax_backend_app.location', verbose_name='Kontinent'),
        ),
        migrations.AlterField(
            model_name='location',
            name='kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kingdom_locations', to='atarax_backend_app.location', verbose_name='Království'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_locations', to='atarax_backend_app.location', verbose_name='Region'),
        ),
    ]
